#!\bin\bash
# i3 panel config. Powerline style.

panel_fifo="/tmp/i3_lemonbar_${USER}"
geometry="x14"
font="-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1"
iconfont="Siji:size=9"
res_w=$(xrandr | grep "current" | awk '{print $8a}')
snd_cha=$(amixer get Master | grep "Playback channels:" | awk '{if ($4 == "") {printf "%s: Playback", $3} else {printf "%s %s: Playback", $3, $4}}')

# Alarm settings
cpu_alert=75                        # % cpu use
net_alert=5                         # K net use

# update setting, in seconds (conky update in i3_lemonbar_conky
upd_vol=1                           # Volume update
upd_mail=300                        # Mail check update
upd_mpd=5                           # MPD song update

# color definitions
color_back="#CC2f343f"              # Default background
color_fore="#CCC5C8C6"              # Default foreground
color_head="#CC5f819d"              # Background for first element
color_sec_b1="#CC282A2E"            # Background for section 1
color_sec_b2="#CC454A4F"            # Background for section 2
color_sec_b3="#CC60676E"            # Background for section 3
color_icon="#CCAFAFAF"              # For icons
color_mail="#CC8c9440"              # Background color for mail alert
color_chat="#CCCC6666"              # Background color for chat alert
color_cpu="#CCa54242"               # Background color for cpu alert
color_net="#CC5E8D87"               # Background color for net alert
color_disable="#CC1D1F21"           # Foreground for disable elements
color_wsp="#CCb5bd68"               # Background for selected workspace
color_bat="#CCA54242"               # Backround for battery
#default space between sections
if [ ${res_w} -gt 1024 ]; then
  stab='  '
else
  stab=' '
fi

# Char glyps for powerline fonts
sep_left=""                        # Powerline separator left
sep_right=""                       # Powerline separator right
sep_l_left=""                      # Powerline light separator left
sep_l_right=""                     # Powerline light sepatator right

# Icon glyphs from Terminusicons2
icon_clock=""                      # Clock icon
icon_cpu=""                        # CPU icon
icon_mem=""                        # MEM icon
icon_dl=""                         # Download icon
icon_ul=""                         # Upload icon
icon_vol=""                        # Volume icon
icon_hd=""                         # HD / icon
icon_mail=""                       # Mail icon
icon_music=""                      # Music icon
icon_prog=""                    # Window icon
icon_wsp=""                        # Workspace icon
icon_bat=""			    # Battery icon
